# Generated by Django 4.1.4 on 2022-12-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='starts_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='member',
            name='plan',
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.ManyToManyField(to='main.plan'),
        ),
    ]
