# Generated by Django 4.1.4 on 2022-12-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_member_options_remove_member_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='mentor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.mentor'),
            preserve_default=False,
        ),
    ]
