# Generated by Django 4.1.4 on 2022-12-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_mentor_plan_plan_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='main.plan'),
        ),
    ]
