# Generated by Django 4.1.4 on 2022-12-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_member_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tags',
            field=models.ManyToManyField(related_name='plans', to='main.tag'),
        ),
    ]
