# Generated by Django 4.1.4 on 2022-12-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_plan_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='featured_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.plan'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tags',
        ),
        migrations.AddField(
            model_name='plan',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='main.tag'),
            preserve_default=False,
        ),
    ]
