# Generated by Django 4.1.4 on 2022-12-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tag_featured_plan_remove_plan_tags_plan_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='featured_plan',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tags',
        ),
        migrations.AddField(
            model_name='plan',
            name='tags',
            field=models.ManyToManyField(related_name='plans', to='main.tag'),
        ),
    ]
