# Generated by Django 4.1.4 on 2023-01-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_mentor_profile_plan_members_alter_plan_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='members',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ManyToManyField(to='main.plan')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
